'use client';
import { useEffect, useState } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell, TableCaption } from '@/components/ui/table';
import { sampleRows, processRows } from '@/lib/demo-data';
const Arrow = () => <span aria-hidden="true">↗</span>;
const assetBase = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
function DataLab() {
 const [repaired, setRepaired] = useState(false);
 const [tab, setTab] = useState('source');
 const rows = repaired ? sampleRows.filter((_, i) => i !== 3).map(row => row.amount === null ? {...row, amount:140} : row) : sampleRows;
 const result = processRows(rows);
 return <div className="data-lab"><div className="lab-top"><span><i className="dot"/> pipeline.playground</span><span>FICTIONAL DATA</span></div>
 <Tabs value={tab} onValueChange={value => setTab(String(value))}><TabsList className="lab-tabs" aria-label="Explore the sample pipeline"><TabsTrigger value="source">01 Source</TabsTrigger><TabsTrigger value="quality">02 Validate</TabsTrigger><TabsTrigger value="output">03 Insights</TabsTrigger></TabsList>
 <TabsContent value="source" className="lab-panel"><div className="panel-heading"><h3>Start with the raw data.</h3><span>{rows.length} rows</span></div><p>Mixed casing, a duplicate, and a missing value. Small problems with downstream consequences.</p><Table className="sample-table"><TableCaption>Fictional orders. Amounts are illustrative units.</TableCaption><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Region</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader><TableBody>{rows.map((row,i) => <TableRow key={i}><TableCell>{row.id}</TableCell><TableCell>{row.region}</TableCell><TableCell>{row.amount ?? <span className="null-value">NULL</span>}</TableCell></TableRow>)}</TableBody></Table><button className="primary-button" onClick={() => setTab('quality')}>Inspect data quality <Arrow/></button></TabsContent>
 <TabsContent value="quality" className="lab-panel"><div className="panel-heading"><h3>Trust starts with validation.</h3><span>{result.issues.length} issues</span></div><p>Check unique IDs and non-negative amounts, then normalize region names.</p><div className="quality-stats"><div><strong>{rows.length}</strong><span>Input rows</span></div><div><strong>{result.accepted.length}</strong><span>Accepted</span></div><div><strong>{result.issues.length}</strong><span>Quarantined</span></div></div><div className="issues" aria-live="polite">{result.issues.length ? result.issues.map(issue => <div key={issue.row}><span>! Row {issue.row} · {issue.id}</span><strong>{issue.reason}</strong></div>) : <div className="quality-success">✓ All sample rows pass the checks.</div>}</div><button className="secondary-button" onClick={() => setRepaired(!repaired)}>{repaired ? 'Restore original issues' : 'Apply sample fixes'}</button><p className="lab-note">The sample fix removes the duplicate and sets A104 to 140. It changes this demo only.</p><button className="primary-button" onClick={() => setTab('output')}>Explore the clean output <Arrow/></button></TabsContent>
 <TabsContent value="output" className="lab-panel"><div className="panel-heading"><h3>From rows to a clearer picture.</h3><span>{result.accepted.length} valid rows</span></div><p>Totals by normalized region, calculated from accepted rows in your browser.</p><div className="result-chart" role="img" aria-label={Object.entries(result.totals).map(([region,total]) => `${region}: ${total}`).join(', ')}>{Object.entries(result.totals).sort().map(([region,total]) => <div key={region}><span>{region}</span><div><i style={{width:`${total/500*100}%`}}/></div><strong>{total}</strong></div>)}</div><pre className="sql-code"><code>{'SELECT region, SUM(amount) AS total\nFROM validated_orders\nGROUP BY region;'}</code></pre><p className="lab-note">Equivalent SQL shown for illustration; this demo runs JavaScript, not a database server.</p><button className="secondary-button" onClick={() => setRepaired(!repaired)}>{repaired ? 'Compare original data' : 'Compare repaired data'}</button><p className="demo-status" role="status">{repaired ? 'Repaired sample: 7 accepted rows.' : 'Original sample: 6 accepted rows; 2 quarantined.'}</p></TabsContent>
 </Tabs></div>;
}
export default function Home() {
 const [activeSection,setActiveSection] = useState('');
 const [copyStatus,setCopyStatus] = useState('');
 useEffect(() => {
  const observer = new IntersectionObserver(entries => { for (const entry of entries) if(entry.isIntersecting) setActiveSection(entry.target.id); },{rootMargin:'-20% 0px -50% 0px'});
  document.querySelectorAll('section[id]').forEach(section => observer.observe(section));
  return () => observer.disconnect();
 },[]);
 async function copyProfile() { try { await navigator.clipboard.writeText('https://www.linkedin.com/in/priyanshugupta01'); setCopyStatus('Profile link copied ✓'); } catch { setCopyStatus('Please use the LinkedIn link to open the profile.'); } }
 return <><a className="skip" href="#main">Skip to content</a>
 <header className="site-header"><a className="brand" href="#" aria-label="Priyanshu Gupta home">pg<span>↗</span></a><nav aria-label="Main navigation">{[['work','Explore'],['about','About'],['contact','Contact']].map(([id,label]) => <a key={id} href={'#'+id} aria-current={activeSection===id?'location':undefined}>{label}{id==='contact' && <> <Arrow/></>}</a>)}</nav></header>
 <main id="main"><section className="hero portrait-hero" id="intro"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> PRIYANSHU GUPTA — DATA ENGINEER</div><h1>Complex data.<br/><span>Clearer</span><br/><em>possibilities.</em></h1><p className="intro-text">Data engineering, SQL, and a practical approach to solving problems. Turning database questions into clear next steps.</p><a className="round-link" href="#work"><span>Explore the data lab</span><b aria-hidden="true">↓</b></a><div className="hero-tech"><span>PostgreSQL</span><span>SQL Server</span><span>ETL</span><span>Python</span></div></div><div className="portrait-wrap"><div className="portrait-frame"><img src={`${assetBase}/images/priyanshu-1000.webp`} srcSet={`${assetBase}/images/priyanshu-640.webp 640w, ${assetBase}/images/priyanshu-1000.webp 1000w`} sizes="(max-width: 760px) 88vw, 40vw" width="1000" height="1333" alt="Priyanshu Gupta seated in a maroon polo shirt" fetchPriority="high"/><div className="portrait-caption"><span>BEHIND THE QUERIES</span><strong>Hi, I’m Priyanshu.</strong></div></div><div className="photo-tag"><span aria-hidden="true">✳</span> A curious mind.<br/>A practical approach.</div></div></section>
 <div className="hero-index"><span>DATA × PROBLEM SOLVING</span><span>EXPLORE. TEST. UNDERSTAND. ↓</span></div>
 <section id="work" className="work lab-section"><div className="section-heading"><h2>Less static.<br/><span className="heading-emphasis">More hands-on.</span></h2><p>A small, working data experiment.<br/>Explore it at your own pace.</p></div><div className="lab-layout"><div className="lab-story"><div className="eyebrow">01 / INTERACTIVE DEMO</div><h3>Good insights<br/>need good data.</h3><p>Follow a tiny dataset from messy input to validated output. Inspect the issues, apply a sample fix, and see the totals change.</p><div className="skills"><span>Validation</span><span>Transformation</span><span>Aggregation</span></div><div className="concept-note"><span>DEMO, NOT CLIENT WORK</span><p>Built for this portfolio with fictional order data. No employer or customer information is used.</p></div></div><DataLab/></div></section>
 <section id="about" className="about personal-about"><div><div className="eyebrow">A LITTLE ABOUT ME</div><img className="about-portrait" src={`${assetBase}/images/priyanshu-640.webp`} width="640" height="853" loading="lazy" alt="Another crop of Priyanshu’s portrait"/></div><div><h2>Data-minded.<br/><span>Solution-oriented.</span></h2><p>I’m Priyanshu Gupta, a Senior Data Engineer at Nath Outsourcing Solutions Pvt. Ltd. My professional focus includes PostgreSQL, SQL Server, ETL, and Python.</p><p>My earlier experience at Data Nova was primarily in support, with database work alongside it. Troubleshooting and root cause analysis remain an important part of how I approach technical problems.</p><div className="skills"><span>PostgreSQL · SQL Server</span><span>ETL · Python</span><span>Troubleshooting · RCA</span></div><a className="text-link" href="https://www.linkedin.com/in/priyanshugupta01" target="_blank" rel="noreferrer">More about my background <Arrow/></a></div></section>
 <section className="approach-section"><div className="section-heading"><h2>How I think about the work.</h2><span className="eyebrow">CLARITY BEFORE COMPLEXITY</span></div><Accordion defaultValue={['data']} className="approach-accordion"><AccordionItem value="data"><AccordionTrigger><span className="approach-index">01</span><span>Understand the data</span></AccordionTrigger><AccordionContent><p>Start with the source, the expected shape, and what “correct” means. In the demo above, even one missing value changes the result.</p></AccordionContent></AccordionItem><AccordionItem value="problem"><AccordionTrigger><span className="approach-index">02</span><span>Investigate the actual problem</span></AccordionTrigger><AccordionContent><p>Trace an issue back to its cause. Separate a symptom from a data-quality problem, an incorrect assumption, or a broken workflow.</p></AccordionContent></AccordionItem><AccordionItem value="clear"><AccordionTrigger><span className="approach-index">03</span><span>Make the result understandable</span></AccordionTrigger><AccordionContent><p>Show what changed, why it matters, and what still needs attention. Useful output should be explainable to the next person who works with it.</p></AccordionContent></AccordionItem></Accordion></section>
 <section id="contact" className="contact"><div className="eyebrow">LET’S CONNECT</div><h2>Good work starts<br/><em>with a conversation.</em></h2><div className="contact-bottom"><p>Data, databases, or a problem worth solving.</p><div className="contact-actions"><a className="primary-button" href="https://www.linkedin.com/in/priyanshugupta01" target="_blank" rel="noreferrer">Connect on LinkedIn <Arrow/></a><button className="secondary-button" onClick={copyProfile}>Copy profile link</button><span className="copy-status" role="status">{copyStatus}</span></div></div></section>
 </main><footer><a className="brand" href="#" aria-label="Back to top">pg<span>↗</span></a><p>© 2026 Priyanshu Gupta.</p><a href="#">Back to top ↑</a></footer></>;
}
